version: '3.9'

services:
  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7

  celery:
    build: .
    command: celery -A mysite worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A mysite beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static:
  media:


